namespace LanHub.Core.Localization;

/// <summary>Lightweight zh/en string table. Call <see cref="SetLanguage"/> then re-apply UI.</summary>
public static class Loc
{
    public const string Zh = "zh";
    public const string En = "en";

    private static string _lang = Zh;
    private static Dictionary<string, string> _map = null!;

    static Loc() => _map = ZhMap;

    public static string Language => _lang;
    public static bool IsEnglish => _lang == En;

    public static event Action? LanguageChanged;

    public static void SetLanguage(string? lang)
    {
        var next = string.Equals(lang, En, StringComparison.OrdinalIgnoreCase) ? En : Zh;
        var changed = _lang != next;
        _lang = next;
        _map = _lang == En ? EnMap : ZhMap;
        if (changed) LanguageChanged?.Invoke();
    }

    public static string T(string key) =>
        _map.TryGetValue(key, out var s) ? s : key;

    public static string Tf(string key, params object?[] args) =>
        string.Format(T(key), args);

    private static readonly Dictionary<string, string> ZhMap = new()
    {
        ["nav.lobby"] = "大厅",
        ["nav.library"] = "游戏库",
        ["nav.settings"] = "设置",
        ["label.display_name"] = "显示名",

        ["banner.eyebrow"] = "精选",
        ["banner.title"] = "局域网派对大厅",
        ["banner.sub"] = "同一 Wi‑Fi 下开房或加入，用房间号校验，经 SDK 互联开玩。",
        ["banner.host"] = "创建房间",
        ["banner.join"] = "加入房间",
        ["banner.shortcuts"] = "快捷入口",
        ["card.host_tag"] = "主机",
        ["card.host_title"] = "开房联机",
        ["card.host_desc"] = "生成房间号，等待好友加入后开始会话。",
        ["card.client_tag"] = "客户端",
        ["card.client_title"] = "发现并加入",
        ["card.client_desc"] = "自动发现同网主机，输入房间号即可进房。",

        ["common.back"] = "返回",
        ["host.title"] = "主机大厅",
        ["host.room_code"] = "房间号",
        ["host.create"] = "开房",
        ["host.copy"] = "复制",
        ["host.dissolve"] = "解散",
        ["host.select_game"] = "选择游戏",
        ["host.start"] = "开始会话",
        ["host.members"] = "成员",
        ["host.kick"] = "踢出",
        ["host.opened"] = "房间已开。对方加入后点「开始会话」，或双方从游戏库打开同一款游戏即可联机",
        ["host.dissolved"] = "房间已解散",
        ["host.create_fail"] = "开房失败",
        ["host.need_room"] = "请先开房",
        ["host.need_game"] = "请先在游戏库添加并选择一款游戏。",
        ["host.start_fail"] = "开始失败",
        ["host.started"] = "已启动 {0}（GameId={1}）— 对方请打开同款",
        ["host.core.opened"] = "房间已开，房间号 {0}；GameUDP {1}:{2}",
        ["host.core.bound"] = "已绑定 {0}，双方从游戏库打开同款游戏即可联机",
        ["host.core.start_sent"] = "已发送开始指令（不可靠走 UDP P2P/主机中继）",
        ["host.core.accept_fail"] = "接受连接失败: {0}",
        ["host.reject.started"] = "房间已开始",
        ["host.reject.code"] = "房间号错误",
        ["host.reject.full"] = "房间已满",
        ["host.reject.rate"] = "尝试过于频繁",
        ["host.reject.invalid"] = "无效加入请求",
        ["client.core.session_updated"] = "会话已更新",
        ["client.core.host_bound"] = "主机已绑定 {0}，请从游戏库打开同款游戏联机",

        ["client.title"] = "加入房间",
        ["client.hosts"] = "发现的主机",
        ["client.room_code"] = "房间号",
        ["client.join"] = "加入",
        ["client.ready"] = "准备",
        ["client.unready"] = "取消准备",
        ["client.leave"] = "离开",
        ["client.open_bound"] = "打开已绑定游戏",
        ["client.members"] = "成员",
        ["client.already_in"] = "你已在房间中。如需重新加入，请先点「离开」。",
        ["client.already_title"] = "已在房间",
        ["client.pick_host"] = "请先在左侧列表中点选一个主机",
        ["client.pick_title"] = "未选择主机",
        ["client.need_code"] = "请输入 6 位房间号",
        ["client.joining"] = "正在加入 {0}:{1} …",
        ["client.joined_bound"] = "已连接。主机已绑定「{0}」，正在自动打开…",
        ["client.joined_wait"] = "已连接。等待主机「开始会话」或从游戏库打开一款游戏；也可点下方按钮手动打开",
        ["client.join_fail"] = "加入失败",
        ["client.left"] = "已离开",
        ["client.kicked"] = "你被踢出房间",
        ["client.dissolved"] = "房间已解散",
        ["client.host_bound_opening"] = "主机已绑定 {0} — 正在打开同款游戏…",
        ["client.host_started_opening"] = "主机已开始「{0}」— 正在打开…",
        ["client.cannot_open"] = "无法打开",
        ["client.no_bind"] = "主机尚未绑定游戏，或尚未完成进房。",
        ["client.bad_gid_status"] = "主机绑定了异常 GameId「{0}」（旧版随机短码）。请在游戏库双击要玩的游戏；并请主机重启 LanHub 后重新「开始会话」。",
        ["client.bad_gid_msg"] = "主机绑定的 GameId「{0}」不是有效的游戏清单 ID。\n请在游戏库手动双击 ArenaDuel / LanChat。\n主机请使用含 lanhub.game.json 的 exe，并重新开始会话。",
        ["client.bad_gid_title"] = "主机 GameId 异常",
        ["client.missing_status"] = "主机已绑定 {0}，但本地游戏库没有匹配项。请到游戏库添加同款（GameId={0}）后点「打开已绑定游戏」。",
        ["client.missing_msg"] = "本地游戏库找不到 GameId={0} 的游戏。\n请先添加该 exe，并确认 GameId 一致。",
        ["client.missing_title"] = "缺少游戏",
        ["client.core.joined_bound"] = "已加入；主机已绑定 {0}，请从游戏库打开同款游戏",
        ["client.core.joined"] = "已加入房间；GameUDP {0}:{1}。等待主机从游戏库打开一款游戏",
        ["client.core.disconnected"] = "与主机断开",
        ["client.joinable"] = "  · 可加入 ",

        ["library.title"] = "游戏库",
        ["library.sub"] = "登记已接入 SDK 的游戏。库可为空，联机可用 Probe 验证。",
        ["library.add"] = "添加",
        ["library.edit"] = "编辑",
        ["library.remove"] = "删除",
        ["library.dblclick"] = "  · 双击打开",
        ["library.open_fail"] = "打开失败",
        ["library.not_found"] = "找不到游戏文件：\n{0}",
        ["library.not_in_room"] = "尚未完成进房，请稍后再试",
        ["library.manifest_ok"] = "已从清单自动识别：\nGameId = {0}\n标题 = {1}",
        ["library.add_title"] = "添加游戏",
        ["library.wait_host_bind"] = "主机尚未绑定游戏。\n请先让主机点击「开始会话」或从游戏库打开一款游戏。",
        ["library.wait_host_title"] = "等待主机绑定",
        ["library.gid_mismatch"] = "主机当前绑定的是「{0}」。\n请打开同一款游戏才能联机。\n\n若主机绑定的是类似 ca9c8a7f 的短码，请让主机重启 LanHub 或重新「开始会话」（会自动从 lanhub.game.json 纠正 GameId）。",
        ["library.gid_mismatch_title"] = "GameId 不一致",

        ["settings.title"] = "设置",
        ["settings.sub"] = "个人资料与网络端口。保存后，新开房 / 发现时生效。",
        ["settings.save"] = "保存设置",
        ["settings.profile"] = "个人资料",
        ["settings.profile_hint"] = "在房间成员列表中显示的名称",
        ["settings.display_name"] = "显示名",
        ["settings.max_players"] = "房间人数上限",
        ["settings.max_hint"] = "开房时可加入的最大玩家数（含主机），范围 2–8",
        ["settings.ports"] = "网络端口",
        ["settings.ports_hint"] = "同一台电脑开多个客户端时，请为各实例设置不同端口",
        ["settings.udp"] = "UDP 发现",
        ["settings.tcp"] = "TCP 房间",
        ["settings.sdk"] = "本机 SDK",
        ["settings.game_udp"] = "游戏 UDP",
        ["settings.saved"] = "设置已保存（端口变更将在下次开房/发现时生效）",

        ["launch.fail"] = "启动失败",
        ["launch.no_token"] = "缺少会话 Token，无法联机启动。请先开房或加入房间。",
        ["launch.no_path"] = "游戏路径不存在：\n{0}",
        ["launch.game_fail"] = "启动游戏失败",
        ["launch.client_started"] = "已启动 {0}（GameId={1}）— 等待互通",
        ["launch.invalid_gid"] = "该游戏的 GameId 无效（疑似随机短码）。请确认 exe 同目录有 lanhub.game.json，或在「编辑」中填入双方一致的 GameId（如 arena-duel）。",
        ["client.open_bound_named"] = "打开「{0}」",
        ["dialog.exe_filter"] = "可执行文件|*.exe|全部|*.*",

        ["edit.title"] = "编辑游戏",
        ["edit.field_title"] = "标题",
        ["edit.game_id"] = "GameId",
        ["edit.exe"] = "Exe 路径",
        ["edit.browse"] = "浏览",
        ["edit.args"] = "启动参数",
        ["edit.cancel"] = "取消",
        ["edit.save"] = "保存",

        ["fmt.ready_host"] = "就绪 {0} · 主机 {1}",
        ["fmt.ready"] = "就绪 {0}",
        ["yes"] = "是",
        ["no"] = "否",
        ["true"] = "是",
        ["false"] = "否",
    };

    private static readonly Dictionary<string, string> EnMap = new()
    {
        ["nav.lobby"] = "Lobby",
        ["nav.library"] = "Library",
        ["nav.settings"] = "Settings",
        ["label.display_name"] = "Display name",

        ["banner.eyebrow"] = "Featured",
        ["banner.title"] = "LAN Party Lobby",
        ["banner.sub"] = "Host or join on the same Wi‑Fi. Verify with a room code, then play over the SDK.",
        ["banner.host"] = "Create room",
        ["banner.join"] = "Join room",
        ["banner.shortcuts"] = "Quick start",
        ["card.host_tag"] = "Host",
        ["card.host_title"] = "Host a session",
        ["card.host_desc"] = "Generate a room code and wait for friends to join.",
        ["card.client_tag"] = "Client",
        ["card.client_title"] = "Discover & join",
        ["card.client_desc"] = "Find hosts on your network and join with a room code.",

        ["common.back"] = "Back",
        ["host.title"] = "Host lobby",
        ["host.room_code"] = "Room code",
        ["host.create"] = "Create",
        ["host.copy"] = "Copy",
        ["host.dissolve"] = "Dissolve",
        ["host.select_game"] = "Select game",
        ["host.start"] = "Start session",
        ["host.members"] = "Members",
        ["host.kick"] = "Kick",
        ["host.opened"] = "Room is open. After others join, click Start session — or both open the same game from the library.",
        ["host.dissolved"] = "Room dissolved",
        ["host.create_fail"] = "Failed to create room",
        ["host.need_room"] = "Create a room first",
        ["host.need_game"] = "Add and select a game in the library first.",
        ["host.start_fail"] = "Failed to start",
        ["host.started"] = "Started {0} (GameId={1}) — peers should open the same game",
        ["host.core.opened"] = "Room open, code {0}; GameUDP {1}:{2}",
        ["host.core.bound"] = "Bound {0}. Both sides open the same game from the library to play.",
        ["host.core.start_sent"] = "Start command sent (unreliable via UDP P2P / host relay)",
        ["host.core.accept_fail"] = "Accept failed: {0}",
        ["host.reject.started"] = "Room already started",
        ["host.reject.code"] = "Invalid room code",
        ["host.reject.full"] = "Room is full",
        ["host.reject.rate"] = "Too many attempts",
        ["host.reject.invalid"] = "Invalid join request",
        ["client.core.session_updated"] = "Session updated",
        ["client.core.host_bound"] = "Host bound {0}. Open the same game from the library.",

        ["client.title"] = "Join room",
        ["client.hosts"] = "Discovered hosts",
        ["client.room_code"] = "Room code",
        ["client.join"] = "Join",
        ["client.ready"] = "Ready",
        ["client.unready"] = "Cancel ready",
        ["client.leave"] = "Leave",
        ["client.open_bound"] = "Open bound game",
        ["client.members"] = "Members",
        ["client.already_in"] = "You are already in a room. Leave first to join another.",
        ["client.already_title"] = "Already in room",
        ["client.pick_host"] = "Select a host in the list on the left",
        ["client.pick_title"] = "No host selected",
        ["client.need_code"] = "Enter the 6-digit room code",
        ["client.joining"] = "Joining {0}:{1} …",
        ["client.joined_bound"] = "Connected. Host bound “{0}”; opening automatically…",
        ["client.joined_wait"] = "Connected. Wait for the host to start, or open a game from the library; you can also use the button below.",
        ["client.join_fail"] = "Join failed",
        ["client.left"] = "Left room",
        ["client.kicked"] = "You were kicked",
        ["client.dissolved"] = "Room dissolved",
        ["client.host_bound_opening"] = "Host bound {0} — opening the same game…",
        ["client.host_started_opening"] = "Host started “{0}” — opening…",
        ["client.cannot_open"] = "Cannot open",
        ["client.no_bind"] = "Host has not bound a game yet, or join is incomplete.",
        ["client.bad_gid_status"] = "Host bound an invalid GameId “{0}” (legacy short code). Double-click a game in the library; ask the host to restart LanHub and start again.",
        ["client.bad_gid_msg"] = "Host GameId “{0}” is not a valid manifest ID.\nDouble-click ArenaDuel / LanChat in the library.\nHost should use an exe with lanhub.game.json and start again.",
        ["client.bad_gid_title"] = "Invalid host GameId",
        ["client.missing_status"] = "Host bound {0}, but it is not in your library. Add the same game (GameId={0}), then click Open bound game.",
        ["client.missing_msg"] = "No library game with GameId={0}.\nAdd the exe and make sure GameId matches.",
        ["client.missing_title"] = "Game missing",
        ["client.core.joined_bound"] = "Joined; host bound {0}. Open the same game from the library.",
        ["client.core.joined"] = "Joined; GameUDP {0}:{1}. Waiting for the host to open a game.",
        ["client.core.disconnected"] = "Disconnected from host",
        ["client.joinable"] = "  · joinable ",

        ["library.title"] = "Game library",
        ["library.sub"] = "Register SDK-enabled games. The library may be empty; use Probe to verify online play.",
        ["library.add"] = "Add",
        ["library.edit"] = "Edit",
        ["library.remove"] = "Remove",
        ["library.dblclick"] = "  · double-click to open",
        ["library.open_fail"] = "Open failed",
        ["library.not_found"] = "Game file not found:\n{0}",
        ["library.not_in_room"] = "Not fully joined yet. Try again shortly.",
        ["library.manifest_ok"] = "Detected from manifest:\nGameId = {0}\nTitle = {1}",
        ["library.add_title"] = "Add game",
        ["library.wait_host_bind"] = "Host has not bound a game yet.\nAsk the host to Start session or open a game from the library.",
        ["library.wait_host_title"] = "Waiting for host",
        ["library.gid_mismatch"] = "Host is currently bound to “{0}”.\nOpen the same game to play together.\n\nIf the host bound a short code like ca9c8a7f, ask them to restart LanHub or Start session again (GameId will be fixed from lanhub.game.json).",
        ["library.gid_mismatch_title"] = "GameId mismatch",

        ["settings.title"] = "Settings",
        ["settings.sub"] = "Profile and network ports. Changes apply on the next host/discover session.",
        ["settings.save"] = "Save settings",
        ["settings.profile"] = "Profile",
        ["settings.profile_hint"] = "Name shown in the room member list",
        ["settings.display_name"] = "Display name",
        ["settings.max_players"] = "Max players",
        ["settings.max_hint"] = "Max players per room (including host), range 2–8",
        ["settings.ports"] = "Network ports",
        ["settings.ports_hint"] = "Use different ports when running multiple clients on one PC",
        ["settings.udp"] = "UDP discover",
        ["settings.tcp"] = "TCP room",
        ["settings.sdk"] = "Local SDK",
        ["settings.game_udp"] = "Game UDP",
        ["settings.saved"] = "Settings saved (port changes apply on next host/discover)",

        ["launch.fail"] = "Launch failed",
        ["launch.no_token"] = "Missing session token. Create or join a room first.",
        ["launch.no_path"] = "Game path does not exist:\n{0}",
        ["launch.game_fail"] = "Failed to launch game",
        ["launch.client_started"] = "Started {0} (GameId={1}) — waiting for peers",
        ["launch.invalid_gid"] = "Invalid GameId (looks like a random short code). Ensure lanhub.game.json sits next to the exe, or set a shared GameId in Edit (e.g. arena-duel).",
        ["client.open_bound_named"] = "Open “{0}”",
        ["dialog.exe_filter"] = "Executable|*.exe|All|*.*",

        ["edit.title"] = "Edit game",
        ["edit.field_title"] = "Title",
        ["edit.game_id"] = "GameId",
        ["edit.exe"] = "Exe path",
        ["edit.browse"] = "Browse",
        ["edit.args"] = "Arguments",
        ["edit.cancel"] = "Cancel",
        ["edit.save"] = "Save",

        ["fmt.ready_host"] = "Ready {0} · Host {1}",
        ["fmt.ready"] = "Ready {0}",
        ["yes"] = "Yes",
        ["no"] = "No",
        ["true"] = "Yes",
        ["false"] = "No",
    };
}
